apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Docker\Docker\kompose.exe convert
    kompose.service.expose: "true"
    kompose.service.type: nodeport
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: dummyprovider
  name: dummyprovider
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dummyprovider
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Docker\Docker\kompose.exe convert
        kompose.service.expose: "true"
        kompose.service.type: nodeport
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: dummyprovider
    spec:
      containers:
        - image: 'eu.gcr.io/asci13-sre-challenge/dummy-pdf-or-png:latest'
          name: dummyprovider
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
