version: '3'
services:
  dummyprovider:
    build: ./dummy-pdf-or-png
    ports:
     - "3000:3000"
    image: ${REGISTRY}dummyprovider:${CURRENT_TAG}
  dummyfrontend:
    build: ./dummyfrontend
    depends_on:
      - dummyprovider
    environment:
      - ListenPort=:5555
      - BackendAddress=http://dummyprovider:3000
    ports:
      - "5555:5555"
    image: ${REGISTRY}dummyfrontend:${CURRENT_TAG}