apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Docker\Docker\kompose.exe convert
    kompose.service.expose: "true"
    kompose.service.type: nodeport
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: dummyfrontend
  name: dummyfrontend
spec:
  ports:
    - name: "5555"
      port: 5555
      targetPort: 5555
  selector:
    io.kompose.service: dummyfrontend
  type: NodePort
status:
  loadBalancer: {}
