name: Deployment

on:
  push:
    branches: [ "master" ]
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PROJECT_ID: asci13-sre-challenge
  GKE_CLUSTER: asci13-sre-challenge-gke   # Add your cluster name here.
  GKE_ZONE: europe-west1   # Add your cluster zone here.
  DEPLOYMENT_NAME: gke-test # Add your deployment name here.
  IMAGE: static-site

jobs:

  deploy:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sre

    steps:
    - uses: actions/checkout@v3

    - name: Version repo
      uses: PaulHatch/semantic-version@v5.0.0-alpha2
      id: version
      with:
        bump_each_commit: true

    - name: Get version values
      run: echo '${{ steps.version.outputs.version }}'

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.8.1

    - name: version, lint and package chart.yaml
      run: |
        sed -i 's/^version:.*$/version: ${{ steps.version.outputs.version }}/' charts/sre-spec-chart/Chart.yaml
        sed -i 's/^appVersion:.*$/appVersion: ${{ steps.version.outputs.version }}/' charts/sre-spec-chart/Chart.yaml
        helm lint charts/sre-spec-chart
        helm package charts/sre-spec-chart
    
    - name: Store helm chart as GH artifact
      uses: actions/upload-artifact@v3
      with:
        name: helm charts
        path: ./**/*.tgz
      
    - name: Push dummy-pdf-or-png image
      uses: RafikFarhad/push-to-gcr-github-action@v4.1
      with:
        gcloud_service_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} # can be base64 encoded or plain text
        registry: eu.gcr.io
        project_id: asci13-sre-challenge
        image_name: dummy-pdf-or-png
        image_tag: latest,${{ steps.version.outputs.version }}
        context: ./sre/dummy-pdf-or-png

    - name: Push frontend image
      uses: RafikFarhad/push-to-gcr-github-action@v4.1
      with:
        gcloud_service_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} # can be base64 encoded or plain text
        registry: eu.gcr.io
        project_id: asci13-sre-challenge
        image_name: dummyfrontend
        image_tag: latest,${{ steps.version.outputs.version }}
        context: ./sre/dummyfrontend

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.8.1

    - run: |-
        file=ls *.tgz
        helm install $file