name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sre

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker images
      run: docker-compose build

    - name: Version repo
      uses: PaulHatch/semantic-version@v5.0.0-alpha2
      id: version
      with:
        bump_each_commit: true
    - name: Get version values
      run: echo '${{ steps.version.outputs.version }}'

    - name: Push Frontend image to registry
      uses: mattes/gce-docker-push-action@v1.0.0
      with:
        creds: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        src: dummyfrontend:build
        dst: gcr.io/asci13-sre-challenge/dummyfrontend:${{ steps.version.outputs.version }}

    - name: Push Dummyprovider image to registry
      uses: mattes/gce-docker-push-action@v1.0.0
      with:
        creds: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        src: dummyprovider:build
        dst: gcr.io/asci13-sre-challenge/dummyprovider:${{ steps.version.outputs.version }}





