name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sre

    steps:
    - uses: actions/checkout@v3

    - name: Version repo
      uses: PaulHatch/semantic-version@v5.0.0-alpha2
      id: version
      with:
        bump_each_commit: true
    - name: Get version values
      run: echo '${{ steps.version.outputs.version }}'

    - name: Push frontend image
      uses: RafikFarhad/push-to-gcr-github-action@v4.1
      with:
        gcloud_service_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} # can be base64 encoded or plain text
        registry: eu.gcr.io
        project_id: asci13-sre-challenge
        image_name: dummyfrontend
        image_tag: latest,${{ steps.version.outputs.version }}
        dockerfile: ./dummyfrontend/Dockerfile
